### ISSUE TITLE
Vector Tile Roadmap

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/3d-tiles#25]
Notes on [vector data](https://github.com/AnalyticalGraphicsInc/3d-tiles/blob/master/TileFormats/VectorData/README.md)

* [ ] Polygons, #24
* [ ] Polylines
* [ ] Points
   * Batch Table semantics for labels and billboards?  Declutter?

Selection of Cesium [geometries](http://cesiumjs.org/2013/11/04/Geometry-and-Appearances/):

* [ ] Polygon: extrusion and at height
* [ ] Polyline: extrusion (wall) and at height
* [ ] Rectangle: on terrain, extrusion, and at height 
* [ ] Ellipse: on terrain, extrusion, and at height 
* Others as requested

**Comment by pjcozzi** [comment]
Initial Cesium implementation for polygons: https://github.com/AnalyticalGraphicsInc/cesium/pull/4186

**Comment by pjcozzi** [comment]
Started spec in #124.

Pushing post 1.0 to narrow the scope, this would come soon after in a follow-up spec release since the spec and Cesium implementation are far along.

**Comment by pjcozzi** [comment]
* [ ] In declarative styling, should `point.image` be able to reference pixels glTF buffer/bufferView style?

**Comment by pjcozzi** [comment]
* [ ] Ability to change polyline width (and other polyline properties) via declarative styling

**Comment by pjcozzi** [comment]
* [ ] Polyline style

**Comment by pjcozzi** [comment]
* [ ] What classification volumes - and other higher order surfaces like ellipses - should be able to be just rendered like polygons - as opposed to used for classifying another tileset?

**Comment by ggetz** [comment]
Suggestion from the forum: https://groups.google.com/forum/#!topic/cesium-dev/3zTt9rZVX08

Ability to style what happens when geometries intersect or overlap (for instance, when two points overlap, ability to define the resulting overlap color)

**Comment by lilleyse** [comment]
* [ ] Make polyline heights optional. When heights are omitted the polyline should be clamped to the surface by the client.

**Comment by lilleyse** [comment]
* [ ] Support textured polygons.

**Comment by pjcozzi** [comment]
## Related

* [flatgeobuf](https://github.com/bjornharrtell/flatgeobuf) - "A performant binary encoding for geographic data based on flatbuffers"

**Comment by jailln** [comment]
Hello, 
Do you have an idea on when the vector tile format will be available in 3D Tiles ?
Thanks :)

**Comment by ruruiye** [comment]
when will this be available? we are waiting for this important feature

**Comment by lilleyse** [comment]
See https://github.com/CesiumGS/3d-tiles/issues/391 for floating point precision considerations.
